services:
  laravel-docker:
    container_name: laravel-docker
    build: ./configPC-laravel
    ports:
      - 8000:80
    volumes:
      - ~/storage:/var/www/app/storage

  vue-docker:
    container_name: vue-docker
    build: ./configpc-react
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: configpc
    ports:
      - 3306:3306