name: configpc-app

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Test-api
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install Docker Compose
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Start docker-compose
      run: docker-compose up -d

    - name: Sleep to ensure containers are ready
      run: sleep 10

    - name: Migrate and seed database
      run: docker exec laravel-docker bash -c "php artisan migrate:fresh --seed"

    - name: Show Laravel logs on failure
      if: failure()
      run: docker exec laravel-docker bash -c "cat storage/logs/laravel.log || true"

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
