name: configpc-app

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Test-api
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.2.0
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Migrate and seed
      run: docker exec laravel-docker php artisan migrate:fresh --seed
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: install jest v1
      run: npm install -g jest
    - name: Run tests
      run: npm run test 
    - name: Show Laravel logs on failure
      if: failure()
      run: docker exec laravel-docker cat storage/logs/laravel.log || true
    # This workflow configuration file defines the CI (Continuous Integration) pipeline.
    # It is located in the .github/workflows directory and is triggered by changes in the repository.
