name: configpc-app

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Test-api

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Docker
        uses: hoverkraft-tech/compose-action@v2.2.0

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Fix storage permissions
        run: docker exec laravel-docker chmod -R 777 storage bootstrap/cache
      - name: Migrate and seed
        run: docker exec laravel-docker php artisan migrate:fresh --seed

      - name: Wait for Laravel to be ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000/api/login | grep -q "Unauthorized"; then
              echo "Laravel is up!"
              break
            else
              echo "Waiting for Laravel to be ready..."
              sleep 3
            fi
          done

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install Jest
        run: npm install -g jest

      - name: Run tests
        run: npm run test

      - name: Show Laravel logs on failure
        if: failure()
        run: docker exec laravel-docker cat storage/logs/laravel.log || true

  build-and-push-image-api-prod:
      needs:
        - tests
      permissions: write-all
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: https://ghcr.io
            username: levprost
            password: Gonka8245@
        - name: Build and push Docker image
          uses: docker/build-push-action@v6
          with:
            context: ./ConfigPC-dev
            build-args: |
              "MODE=prod"
            push: true
            tags: |
              ghcr.io/levprost/ConfigPC-dev-prod:latest
              ghcr.io/levprost/ConfigPC-dev-prod:${{ github.sha }}
  build-and-push-image-spa-prod:
    needs:
      - tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: levprost
          password: Gonka8245@
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ConfigPC-dev
          build-args: |
            "MODE=prod"
          push: true
          tags: |
            ghcr.io/levprost/ConfigPC-dev-prod:latest
            ghcr.io/levprost/ConfigPC-dev-prod:${{ github.sha }}